openapi: 3.0.0
info:
  title: StitchSure API Documentation
  version: 1.0.0
  description: API documentation for the StitchSure application, which connects customers with tailors and designers for custom clothing services.
paths:
  /api/v1/customer/register:
    post:
      summary: Create a new customer
      tags: [customer]

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - firstName
                - lastName
                - email
                - password
              properties:
                firstName:
                  type: string
                  example: John
                  description: "The first name of the customer"
                lastName:
                  type: string
                  example: Doe
                  description: "The last name of the customer"
                email:
                  type: string
                  example: johndoe@gmail.com
                  description: "The email address of the customer"
                password:
                  type: string
                  example: Password123!
                  description: "The password for the customer's account"
      responses:
        '201':
          description: Account created successfully
  /api/v1/customer/login:
    post:
      summary: Customer login
      tags: [customer]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: johndoe@gmail.com
                  description: "The email address of the customer"
                password:
                  type: string
                  example: Password123!
                  description: "The password for the customer's account"
      responses:
        '200':
          description: Logged in successfully 
  /api/v1/customer/forget-password:
    post:
      summary: Customer forget password
      tags: [customer]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: johndoe@gmail.com
                  description: "The email address of the customer"
      responses:
        '200':
          description: Password reset successfully
  /api/v1/customer/reset-password:
    post:
      summary: Customer reset password
      tags: [customer]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
               - password
              properties:
                password:
                  type: string
                  example: Password123!
                  description: "The new password for the customer's account"
      responses:
        '200':
          description: Password updated successfully
  /api/v1/customer/verify:
    post:
      summary: 
      tags: [customer]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
                - email
              properties:
                otp:
                  type: string
                email:
                  type: string
                  example: johndoe@gmail.com
      responses:
        '200':
          description: Verified successfully
  /api/v1/customer/update-profile/{id}:
    put:
      summary: Update customer profile
      parameters:
        - in: path
          name: id
      tags: [customer]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  example: John
                lastName:
                  type: string
                  example: Doe
                email:
                  type: string
                  example: johndoe@gmail.com
                profilePhoto:
                  type: string
                  format: binary
      responses:
        '200':
          description: Profile updated successfully
